version: "3"
services:
  appseguridad:
    image: ${DOCKER_REGISTRY}roxfarma-appseguridad
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${DOMAIN_APP}
      - LETSENCRYPT_HOST=${DOMAIN_APP}
      - LETSENCRYPT_EMAIL=${EMAIL}
volumes:
  certs:
  html:
  vhostd:
networks:
  default:
    name: roxfarma-network